### ISSUE TITLE
awsecr-creds pod crashes

### ISSUE THREAD

**Issue by vincent-dm** [upmc-enterprises/awsecr-creds#21]
I have set up the secret (with the AWS access key, secret access key and account id) and the replication controller in namespace kube-system, but the pod keeps crashing  (CrashLoopBackOff)

```
2016-12-28T11:14:10.257472708Z 2016/12/28 11:14:10 Starting up...
2016-12-28T11:14:10.257526395Z 2016/12/28 11:14:10 Using AWS Account: 7########4
2016-12-28T11:14:10.257563600Z 2016/12/28 11:14:10 Refresh Interval (minutes): 715
2016-12-28T11:14:10.454424907Z InvalidParameterException: Invalid parameter at 'registryIds' failed to satisfy constraint: 'Member must satisfy constraint: [Member must satisfy regular expression pattern: [0-9]{12}]'
2016-12-28T11:14:10.454509660Z 	status code: 400, request id: c19e2b6a-ccee-11e6-9ad2-45244efed646
2016-12-28T11:14:10.457277072Z panic: runtime error: invalid memory address or nil pointer dereference
2016-12-28T11:14:10.457343399Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4015b1]
2016-12-28T11:14:10.457353435Z 
2016-12-28T11:14:10.457359391Z goroutine 1 [running]:
2016-12-28T11:14:10.457364816Z panic(0x13bb560, 0xc420014020)
2016-12-28T11:14:10.457370628Z 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
2016-12-28T11:14:10.457426418Z main.process()
2016-12-28T11:14:10.457437499Z 	/Users/slokas/godev/src/enterprises.io/andrew/awsecr-creds/aws_credentials.go:106 +0x91
2016-12-28T11:14:10.457443905Z main.main()
2016-12-28T11:14:10.457449377Z 	/Users/slokas/godev/src/enterprises.io/andrew/awsecr-creds/aws_credentials.go:186 +0x3c0
```

The (censored) contents of my secret:
```yaml
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: QUtJ############E=
  AWS_SECRET_ACCESS_KEY: VGN################################lzNA==
  aws-account: N############Cg==
kind: Secret
metadata:
  creationTimestamp: 2016-12-28T11:13:06Z
  labels:
    app: awsecr-creds
    kubernetes.io/minikube-addons: awsecr-creds
    version: v1.2
  name: awsecr-creds
  namespace: kube-system
  resourceVersion: "2379"
  selfLink: /api/v1/namespaces/kube-system/secrets/awsecr-creds
  uid: 9b86eb41-ccee-11e6-b2d8-feb8681bd404
type: Opaque
```
(I checked and the b64 encoding of the AWS params is correct, since I can view the right contents via the minikube dashboard)

My replication controller:
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: awsecr-creds
  namespace: kube-system
  labels:
    version: v1.2
spec:
  replicas: 1
  selector:
    name: awsecr-creds
    version: v1.2
  template:
    metadata:
      labels:
        name: awsecr-creds
        version: v1.2
    spec:
      containers:
      - image: upmcenterprises/awsecr-creds:1.2
        name: awsecr-creds
        args:
        - "--aws-region=eu-west-1"
        imagePullPolicy: Always
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: awsecr-creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: awsecr-creds
                key: AWS_SECRET_ACCESS_KEY
          - name: awsaccount
            valueFrom:
              secretKeyRef:
                name: awsecr-creds
                key: aws-account
```

Any idea why it is crashing?

**Comment by vincent-dm** [comment]
PS: I double-checked and my account ID is 12 digits, so it seems like the regex is parsing something else...

**Comment by vincent-dm** [comment]
I found that I can work around the problem by specifying the awsaccount directly in the replication controller. My gut feeling is that it is some kind of int vs string problem.

I used `echo 7##########4 | base64` to create the values in the secret.

**Comment by vincent-dm** [comment]
Seems that I forgot to add the -n flag to echo
🙄
